---
title: "Class Examples"
author: "Jessica Flynn"
output: html_document
---

```{r}
library(tidyverse)
library(p8105.datasets)
library(rvest)
library(httr)


theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
```

## Restaurant Inspections

```{r}
api_url = "https://data.cityofnewyork.us/resource/43nn-pn8j.csv"

rest_inspection = GET(api_url, query = list("$limit" = 50000)) %>% 
  content("parsed")

```

```{r}
rest_inspection %>% 
  count(boro, grade) %>% 
  pivot_wider(names_from = grade, 
              values_from = n)
```

```{r}
rest_inspection = 
  rest_inspection %>% 
  filter(grade %in% c("A", "B", "C"), boro != "0")
```

Let's look at pizza places...

```{r}
rest_inspection %>% 
  mutate(dba = str_to_upper(dba)) %>% 
  filter(str_detect(dba, "PIZZ"))
```

```{r}
rest_inspection %>% 
  mutate(dba = str_to_upper(dba)) %>% 
  filter(str_detect(dba, "PIZZ")) %>%
  count(boro, grade) %>% 
  pivot_wider(names_from = grade, 
              values_from = n)
```

```{r}
rest_inspection %>% 
  mutate(dba = str_to_upper(dba)) %>% 
  filter(str_detect(dba, "PIZZ")) %>% 
  mutate(boro = fct_infreq(boro), 
         boro = str_replace(boro, "Brooklyn", "HipsterVille")) %>% 
  ggplot(aes(x = boro)) +
  geom_bar() +
  facet_wrap(.~grade)
```

## Napolean Dynamite 

Get Napolean Dynamite Amazon Reviews
```{r}
nap_url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

#Can change to pageNumber=2 to get next 10 reviews

napolean_html = read_html(nap_url)

review_titles = 
  napolean_html %>% 
  html_nodes(".a-text-bold span") %>% 
  html_text()

review_text = 
  napolean_html %>% 
  html_nodes(".review-text-content span") %>% 
  html_text()

nap_df = 
 tibble(
   titles = review_titles, 
   text = review_text
)

```


